### ISSUE TITLE
Is this still work on Hexo-3.0 ?

### ISSUE THREAD

**Issue by Nerom** [hexojs/hexo-deployer-ftpsync#2]
I use this deployer - ftpsync ,and I got this ERROR:
```
TypeError: object is not a function
    at Hexo.<anonymous> (d:\Git-blogs\hexo-blog\node_modules\hexo-deployer-ftpsync\index.js:4:13)
    at Hexo.tryCatcher (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at Hexo.ret (eval at <anonymous> (d:\Git-blogs\hexo-blog\node_modules\hexo-deployer-git\node_modules\hexo-fs\node_modules\bluebird\js\main\promisify.js:154:12),<anonymous>:12:39)
    at d:\Git-blogs\hexo-blog\node_modules\hexo\lib\plugins\console\deploy.js:56:28
    at tryCatcher (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at ReductionPromiseArray._promiseFulfilled (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\reduce.js:103:38)
    at Promise._settlePromiseAt (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:535:26)
    at Promise._settlePromises (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:132:16)
    at Async._drainQueues (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:142:10)
    at Async.drainQueues (d:\Git-blogs\hexo-blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:16:14)
    at process._tickCallback (node.js:442:13)
```
@tommy351

**Comment by Nerom** [comment]
@tommy351 我把`new`那句删掉了，能上传一部分文章，但是会有个错误：
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```
我正在尝试修复这个问题，如果你有什么建议的话，请尽快回复

**Comment by Nerom** [comment]
@tommy351 change the `var ftp = new FTPSync()` to `var ftp = FTPSync` could solve the problem.
because of the `new`problem . And some problems are still in the `ftpsync` module, I'm trying to fix it.
